-- Seed luxury fashion products (Women's Collection)
INSERT INTO products (name_fr, name_en, name_es, name_de, name_it, slug, description_fr, description_en, description_es, description_de, description_it, price, category, subcategory, composition_fr, composition_en, composition_es, composition_de, composition_it, sizes, colors, images, is_featured, is_new) VALUES

-- Women's Dresses
('Robe Élégante en Soie', 'Elegant Silk Dress', 'Vestido Elegante de Seda', 'Elegantes Seidenkleid', 'Abito Elegante in Seta', 'robe-elegante-soie', 
'Une robe raffinée en soie pure qui sublime la silhouette. Coupe fluide et détails délicats pour une élégance intemporelle.', 
'A refined pure silk dress that enhances the silhouette. Fluid cut and delicate details for timeless elegance.',
'Un vestido refinado de seda pura que realza la silueta. Corte fluido y detalles delicados para una elegancia atemporal.',
'Ein raffiniertes Kleid aus reiner Seide, das die Silhouette betont. Fließender Schnitt und zarte Details für zeitlose Eleganz.',
'Un abito raffinato in seta pura che valorizza la silhouette. Taglio fluido e dettagli delicati per un''eleganza senza tempo.',
850.00, 'femme', 'robes', 
'100% Soie', '100% Silk', '100% Seda', '100% Seide', '100% Seta',
ARRAY['XS', 'S', 'M', 'L'], ARRAY['Noir', 'Ivoire', 'Bordeaux'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Robe Midi Plissée', 'Pleated Midi Dress', 'Vestido Midi Plisado', 'Plissiertes Midi-Kleid', 'Abito Midi Plissettato', 'robe-midi-plissee',
'Robe midi sophistiquée avec plissés délicats. Parfaite pour toutes les occasions, elle allie confort et style raffiné.',
'Sophisticated midi dress with delicate pleats. Perfect for all occasions, combining comfort and refined style.',
'Vestido midi sofisticado con pliegues delicados. Perfecto para todas las ocasiones, combina comodidad y estilo refinado.',
'Raffiniertes Midi-Kleid mit zarten Falten. Perfekt für alle Anlässe, vereint Komfort und raffinierten Stil.',
'Abito midi sofisticato con pieghe delicate. Perfetto per ogni occasione, unisce comfort e stile raffinato.',
720.00, 'femme', 'robes',
'65% Polyester, 35% Viscose', '65% Polyester, 35% Viscose', '65% Poliéster, 35% Viscosa', '65% Polyester, 35% Viskose', '65% Poliestere, 35% Viscosa',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Beige', 'Noir', 'Rose Poudré'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, true),

-- Women's Tops
('Chemisier en Satin', 'Satin Blouse', 'Blusa de Satén', 'Satin-Bluse', 'Camicetta di Raso', 'chemisier-satin',
'Chemisier luxueux en satin fluide avec col officier. Pièce intemporelle pour un look sophistiqué au quotidien.',
'Luxurious fluid satin blouse with officer collar. Timeless piece for sophisticated everyday look.',
'Blusa lujosa de satén fluido con cuello oficial. Pieza atemporal para un look sofisticado diario.',
'Luxuriöse fließende Satinbluse mit Offizierskragen. Zeitloses Stück für einen raffinierten Alltags-Look.',
'Camicetta lussuosa in raso fluido con collo alla coreana. Pezzo senza tempo per un look sofisticato quotidiano.',
420.00, 'femme', 'hauts',
'100% Soie Satin', '100% Satin Silk', '100% Satén de Seda', '100% Seidensatin', '100% Raso di Seta',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Blanc', 'Noir', 'Champagne'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

('Pull Cachemire Col V', 'Cashmere V-Neck Sweater', 'Jersey de Cachemira Cuello V', 'Kaschmir-Pullover V-Ausschnitt', 'Maglione Cashmere Scollo V', 'pull-cachemire-col-v',
'Pull ultra-doux en pur cachemire mongol. Finitions impeccables et coupe moderne pour un confort absolu.',
'Ultra-soft pure Mongolian cashmere sweater. Impeccable finishes and modern cut for absolute comfort.',
'Jersey ultra suave de cachemira mongol pura. Acabados impecables y corte moderno para una comodidad absoluta.',
'Ultra-weicher Pullover aus reinem mongolischem Kaschmir. Tadellose Verarbeitung und moderner Schnitt für absoluten Komfort.',
'Maglione ultra morbido in puro cashmere mongolo. Finiture impeccabili e taglio moderno per un comfort assoluto.',
680.00, 'femme', 'hauts',
'100% Cachemire', '100% Cashmere', '100% Cachemira', '100% Kaschmir', '100% Cashmere',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Beige', 'Gris Perle', 'Camel', 'Noir'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

-- Women's Bottoms
('Pantalon Tailleur Droit', 'Straight Tailored Trousers', 'Pantalón Sastre Recto', 'Gerade Anzughose', 'Pantalone Sartoriale Dritto', 'pantalon-tailleur-droit',
'Pantalon tailleur à la coupe parfaite. Ligne épurée et tombé impeccable pour une allure professionnelle raffinée.',
'Tailored trousers with perfect cut. Clean lines and impeccable drape for refined professional look.',
'Pantalón sastre con corte perfecto. Líneas limpias y caída impecable para un aspecto profesional refinado.',
'Maßgeschneiderte Hose mit perfektem Schnitt. Klare Linien und tadelloser Fall für ein raffiniertes professionelles Aussehen.',
'Pantalone sartoriale dal taglio perfetto. Linee pulite e caduta impeccabile per un look professionale raffinato.',
520.00, 'femme', 'bas',
'70% Laine Vierge, 28% Polyester, 2% Élasthanne', '70% Virgin Wool, 28% Polyester, 2% Elastane', '70% Lana Virgen, 28% Poliéster, 2% Elastano', '70% Schurwolle, 28% Polyester, 2% Elasthan', '70% Lana Vergine, 28% Poliestere, 2% Elastan',
ARRAY['34', '36', '38', '40', '42', '44'], ARRAY['Noir', 'Marine', 'Gris Anthracite'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Jupe Midi en Cuir', 'Leather Midi Skirt', 'Falda Midi de Cuero', 'Leder-Midirock', 'Gonna Midi in Pelle', 'jupe-midi-cuir',
'Jupe midi en cuir souple de haute qualité. Silhouette moderne et élégante avec fermeture invisible.',
'High-quality soft leather midi skirt. Modern and elegant silhouette with invisible closure.',
'Falda midi de cuero suave de alta calidad. Silueta moderna y elegante con cierre invisible.',
'Hochwertiger Midirock aus weichem Leder. Moderne und elegante Silhouette mit unsichtbarem Verschluss.',
'Gonna midi in pelle morbida di alta qualità. Silhouette moderna ed elegante con chiusura invisibile.',
890.00, 'femme', 'bas',
'100% Cuir d''Agneau', '100% Lambskin Leather', '100% Cuero de Cordero', '100% Lammleder', '100% Pelle d''Agnello',
ARRAY['34', '36', '38', '40', '42'], ARRAY['Noir', 'Cognac'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, true),

-- Women's Outerwear
('Manteau Long en Laine', 'Long Wool Coat', 'Abrigo Largo de Lana', 'Langer Wollmantel', 'Cappotto Lungo in Lana', 'manteau-long-laine',
'Manteau iconique en laine cachemire. Silhouette fluide et coupe intemporelle pour traverser l''hiver avec style.',
'Iconic cashmere wool coat. Fluid silhouette and timeless cut to get through winter in style.',
'Abrigo icónico de lana cachemira. Silueta fluida y corte atemporal para pasar el invierno con estilo.',
'Ikonischer Kaschmirwollmantel. Fließende Silhouette und zeitloser Schnitt für einen stilvollen Winter.',
'Cappotto iconico in lana cashmere. Silhouette fluida e taglio senza tempo per affrontare l''inverno con stile.',
1450.00, 'femme', 'manteaux',
'80% Laine, 20% Cachemire', '80% Wool, 20% Cashmere', '80% Lana, 20% Cachemira', '80% Wolle, 20% Kaschmir', '80% Lana, 20% Cashmere',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Camel', 'Noir', 'Gris Chiné'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Blazer Structuré', 'Structured Blazer', 'Blazer Estructurado', 'Strukturierter Blazer', 'Blazer Strutturato', 'blazer-structure',
'Blazer structuré parfaitement taillé. Épaules marquées et coupe moderne pour une silhouette affirmée.',
'Perfectly tailored structured blazer. Defined shoulders and modern cut for confident silhouette.',
'Blazer estructurado perfectamente confeccionado. Hombros definidos y corte moderno para una silueta segura.',
'Perfekt geschneiderter strukturierter Blazer. Definierte Schultern und moderner Schnitt für selbstbewusste Silhouette.',
'Blazer strutturato perfettamente sartoriale. Spalle definite e taglio moderno per una silhouette decisa.',
980.00, 'femme', 'manteaux',
'55% Laine, 43% Polyester, 2% Élasthanne', '55% Wool, 43% Polyester, 2% Elastane', '55% Lana, 43% Poliéster, 2% Elastano', '55% Wolle, 43% Polyester, 2% Elasthan', '55% Lana, 43% Poliestere, 2% Elastan',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Noir', 'Blanc Cassé', 'Marine'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

-- Men's Collection
('Costume Sur-Mesure', 'Bespoke Suit', 'Traje a Medida', 'Maßanzug', 'Abito Su Misura', 'costume-sur-mesure',
'Costume deux-pièces d''une élégance absolue. Tissu noble et finitions impeccables pour une allure distinguée.',
'Two-piece suit of absolute elegance. Noble fabric and impeccable finishes for distinguished appearance.',
'Traje de dos piezas de elegancia absoluta. Tejido noble y acabados impecables para una apariencia distinguida.',
'Zweiteiliger Anzug von absoluter Eleganz. Edles Gewebe und tadellose Verarbeitung für distinguiertes Auftreten.',
'Abito due pezzi di eleganza assoluta. Tessuto nobile e finiture impeccabili per un aspetto distinto.',
2100.00, 'homme', 'costumes',
'100% Laine Super 120', '100% Super 120 Wool', '100% Lana Super 120', '100% Super 120 Wolle', '100% Lana Super 120',
ARRAY['44', '46', '48', '50', '52', '54'], ARRAY['Charbon', 'Marine', 'Gris'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Chemise Oxford Premium', 'Premium Oxford Shirt', 'Camisa Oxford Premium', 'Premium Oxford-Hemd', 'Camicia Oxford Premium', 'chemise-oxford-premium',
'Chemise Oxford en coton égyptien. Tissage serré et col italien pour une élégance décontractée.',
'Oxford shirt in Egyptian cotton. Tight weave and Italian collar for casual elegance.',
'Camisa Oxford en algodón egipcio. Tejido apretado y cuello italiano para elegancia casual.',
'Oxford-Hemd aus ägyptischer Baumwolle. Dichtes Gewebe und italienischer Kragen für lässige Eleganz.',
'Camicia Oxford in cotone egiziano. Tessitura stretta e collo italiano per eleganza casual.',
280.00, 'homme', 'chemises',
'100% Coton Égyptien', '100% Egyptian Cotton', '100% Algodón Egipcio', '100% Ägyptische Baumwolle', '100% Cotone Egiziano',
ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Blanc', 'Bleu Ciel', 'Rose Pâle'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Pull Col Roulé Mérinos', 'Merino Turtleneck Sweater', 'Jersey Cuello Alto Merino', 'Merino-Rollkragenpullover', 'Maglione Collo Alto Merino', 'pull-col-roule-merinos',
'Pull col roulé en laine mérinos extra-fine. Douceur incomparable et thermorégulation naturelle.',
'Turtleneck sweater in extra-fine merino wool. Incomparable softness and natural thermoregulation.',
'Jersey cuello alto en lana merino extrafina. Suavidad incomparable y termorregulación natural.',
'Rollkragenpullover aus extrafeiner Merinowolle. Unvergleichliche Weichheit und natürliche Thermoregulation.',
'Maglione collo alto in lana merino extra-fine. Morbidezza incomparabile e termoregolazione naturale.',
390.00, 'homme', 'pulls',
'100% Laine Mérinos Extra-Fine', '100% Extra-Fine Merino Wool', '100% Lana Merino Extrafina', '100% Extrafeine Merinowolle', '100% Lana Merino Extra-Fine',
ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Noir', 'Marine', 'Gris', 'Bordeaux'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

('Pantalon Chino Stretch', 'Stretch Chino Trousers', 'Pantalón Chino Stretch', 'Stretch-Chino-Hose', 'Pantalone Chino Stretch', 'pantalon-chino-stretch',
'Chino moderne avec stretch invisible. Confort optimal et coupe ajustée pour un style urbain sophistiqué.',
'Modern chino with invisible stretch. Optimal comfort and fitted cut for sophisticated urban style.',
'Chino moderno con stretch invisible. Comodidad óptima y corte ajustado para un estilo urbano sofisticado.',
'Moderne Chino mit unsichtbarem Stretch. Optimaler Komfort und angepasster Schnitt für raffinierten urbanen Stil.',
'Chino moderno con stretch invisibile. Comfort ottimale e taglio aderente per uno stile urbano sofisticato.',
240.00, 'homme', 'pantalons',
'97% Coton, 3% Élasthanne', '97% Cotton, 3% Elastane', '97% Algodón, 3% Elastano', '97% Baumwolle, 3% Elasthan', '97% Cotone, 3% Elastan',
ARRAY['44', '46', '48', '50', '52'], ARRAY['Beige', 'Marine', 'Olive', 'Gris'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

-- Accessories
('Sac Cabas en Cuir', 'Leather Tote Bag', 'Bolso Tote de Cuero', 'Leder-Shopper', 'Borsa Tote in Pelle', 'sac-cabas-cuir',
'Grand cabas en cuir grainé de première qualité. Spacieux et élégant, l''accessoire indispensable au quotidien.',
'Large tote in premium grained leather. Spacious and elegant, the essential everyday accessory.',
'Bolso tote grande en cuero granulado premium. Espacioso y elegante, el accesorio esencial diario.',
'Großer Shopper aus erstklassigem genarbtem Leder. Geräumig und elegant, das unverzichtbare Alltags-Accessoire.',
'Grande tote in pelle martellata di prima qualità. Spazioso ed elegante, l''accessorio essenziale quotidiano.',
780.00, 'accessoires', 'sacs',
'100% Cuir de Vachette Grainé', '100% Grained Cowhide Leather', '100% Cuero de Vaca Granulado', '100% Genarbtes Rindleder', '100% Pelle Bovina Martellata',
ARRAY['Unique'], ARRAY['Noir', 'Cognac', 'Taupe'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Écharpe Cachemire', 'Cashmere Scarf', 'Bufanda de Cachemira', 'Kaschmirschal', 'Sciarpa Cashmere', 'echarpe-cachemire',
'Écharpe luxueuse en pur cachemire. Douceur incomparable et chaleur délicate pour affronter l''hiver.',
'Luxurious scarf in pure cashmere. Incomparable softness and delicate warmth for winter.',
'Bufanda lujosa en cachemira pura. Suavidad incomparable y calidez delicada para el invierno.',
'Luxuriöser Schal aus reinem Kaschmir. Unvergleichliche Weichheit und zarte Wärme für den Winter.',
'Sciarpa lussuosa in puro cashmere. Morbidezza incomparabile e calore delicato per l''inverno.',
320.00, 'accessoires', 'echarpes',
'100% Cachemire', '100% Cashmere', '100% Cachemira', '100% Kaschmir', '100% Cashmere',
ARRAY['Unique'], ARRAY['Gris Perle', 'Camel', 'Noir', 'Marine'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

('Ceinture en Cuir Italien', 'Italian Leather Belt', 'Cinturón de Cuero Italiano', 'Italienischer Ledergürtel', 'Cintura in Pelle Italiana', 'ceinture-cuir-italien',
'Ceinture en cuir italien pleine fleur. Boucle métallique sobre et finitions artisanales.',
'Full-grain Italian leather belt. Understated metal buckle and artisanal finishes.',
'Cinturón de cuero italiano de grano completo. Hebilla metálica sobria y acabados artesanales.',
'Gürtel aus italienischem Vollleder. Dezente Metallschnalle und handwerkliche Verarbeitung.',
'Cintura in pelle italiana a pieno fiore. Fibbia metallica sobria e finiture artigianali.',
280.00, 'accessoires', 'ceintures',
'100% Cuir Italien Pleine Fleur', '100% Full-Grain Italian Leather', '100% Cuero Italiano de Grano Completo', '100% Italienisches Vollleder', '100% Pelle Italiana Pieno Fiore',
ARRAY['85', '90', '95', '100', '105'], ARRAY['Noir', 'Marron', 'Cognac'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Lunettes de Soleil Vintage', 'Vintage Sunglasses', 'Gafas de Sol Vintage', 'Vintage-Sonnenbrille', 'Occhiali da Sole Vintage', 'lunettes-soleil-vintage',
'Lunettes de soleil au design vintage intemporel. Verres polarisés de haute qualité et monture acétate.',
'Sunglasses with timeless vintage design. High-quality polarized lenses and acetate frame.',
'Gafas de sol con diseño vintage atemporal. Lentes polarizadas de alta calidad y montura de acetato.',
'Sonnenbrille mit zeitlosem Vintage-Design. Hochwertige polarisierte Gläser und Acetat-Fassung.',
'Occhiali da sole dal design vintage senza tempo. Lenti polarizzate di alta qualità e montatura in acetato.',
420.00, 'accessoires', 'lunettes',
'Monture Acétate, Verres Polarisés', 'Acetate Frame, Polarized Lenses', 'Montura Acetato, Lentes Polarizadas', 'Acetat-Fassung, Polarisierte Gläser', 'Montatura Acetato, Lenti Polarizzate',
ARRAY['Unique'], ARRAY['Noir', 'Écaille', 'Havane'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

-- Additional Women's Items
('Trench Classique', 'Classic Trench Coat', 'Gabardina Clásica', 'Klassischer Trenchcoat', 'Trench Classico', 'trench-classique',
'Trench iconique en gabardine imperméable. Pièce intemporelle alliant élégance britannique et fonctionnalité.',
'Iconic trench in waterproof gabardine. Timeless piece combining British elegance and functionality.',
'Gabardina icónica en gabardina impermeable. Pieza atemporal que combina elegancia británica y funcionalidad.',
'Ikonischer Trench aus wasserdichtem Gabardine. Zeitloses Stück, das britische Eleganz und Funktionalität vereint.',
'Trench iconico in gabardine impermeabile. Pezzo senza tempo che unisce eleganza britannica e funzionalità.',
1280.00, 'femme', 'manteaux',
'100% Coton Gabardine', '100% Cotton Gabardine', '100% Gabardina de Algodón', '100% Baumwoll-Gabardine', '100% Gabardine di Cotone',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Beige', 'Noir', 'Kaki'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Robe Cocktail Brodée', 'Embroidered Cocktail Dress', 'Vestido Cóctel Bordado', 'Besticktes Cocktailkleid', 'Abito Cocktail Ricamato', 'robe-cocktail-brodee',
'Robe cocktail somptueuse avec broderies délicates. Silhouette flatteuse et détails luxueux pour les occasions spéciales.',
'Sumptuous cocktail dress with delicate embroidery. Flattering silhouette and luxurious details for special occasions.',
'Vestido cóctel suntuoso con bordados delicados. Silueta favorecedora y detalles lujosos para ocasiones especiales.',
'Prächtiges Cocktailkleid mit zarten Stickereien. Schmeichelhafte Silhouette und luxuriöse Details für besondere Anlässe.',
'Abito cocktail sontuoso con ricami delicati. Silhouette lusinghiera e dettagli lussuosi per occasioni speciali.',
1650.00, 'femme', 'robes',
'70% Polyester, 30% Soie', '70% Polyester, 30% Silk', '70% Poliéster, 30% Seda', '70% Polyester, 30% Seide', '70% Poliestere, 30% Seta',
ARRAY['XS', 'S', 'M', 'L'], ARRAY['Noir', 'Bleu Nuit', 'Bordeaux'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, true),

('Bottines en Daim', 'Suede Ankle Boots', 'Botines de Ante', 'Wildleder-Stiefeletten', 'Stivaletti in Camoscio', 'bottines-daim',
'Bottines Chelsea en daim souple. Élastiques latéraux et semelle en cuir pour un confort toute la journée.',
'Chelsea ankle boots in soft suede. Side elastics and leather sole for all-day comfort.',
'Botines Chelsea en ante suave. Elásticos laterales y suela de cuero para comodidad todo el día.',
'Chelsea-Stiefeletten aus weichem Wildleder. Seitliche Gummizüge und Ledersohle für ganztägigen Komfort.',
'Stivaletti Chelsea in camoscio morbido. Elastici laterali e suola in pelle per comfort tutto il giorno.',
680.00, 'femme', 'chaussures',
'Tige: Daim, Doublure: Cuir, Semelle: Cuir', 'Upper: Suede, Lining: Leather, Sole: Leather', 'Parte superior: Ante, Forro: Cuero, Suela: Cuero', 'Obermaterial: Wildleder, Futter: Leder, Sohle: Leder', 'Tomaia: Camoscio, Fodera: Pelle, Suola: Pelle',
ARRAY['36', '37', '38', '39', '40', '41'], ARRAY['Noir', 'Taupe', 'Bordeaux'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

('Robe Longue Fluide', 'Fluid Maxi Dress', 'Vestido Largo Fluido', 'Fließendes Maxikleid', 'Abito Lungo Fluido', 'robe-longue-fluide',
'Robe longue en jersey fluide. Coupe empire et mouvement gracieux pour une féminité affirmée.',
'Maxi dress in fluid jersey. Empire cut and graceful movement for confident femininity.',
'Vestido largo en jersey fluido. Corte imperio y movimiento elegante para feminidad segura.',
'Maxikleid aus fließendem Jersey. Empire-Schnitt und anmutige Bewegung für selbstbewusste Weiblichkeit.',
'Abito lungo in jersey fluido. Taglio impero e movimento aggraziato per femminilità decisa.',
520.00, 'femme', 'robes',
'95% Viscose, 5% Élasthanne', '95% Viscose, 5% Elastane', '95% Viscosa, 5% Elastano', '95% Viskose, 5% Elasthan', '95% Viscosa, 5% Elastan',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Vert Émeraude', 'Bleu Marine', 'Terracotta'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

-- Additional Men's Items
('Manteau Caban Marine', 'Navy Pea Coat', 'Chaquetón Marinero Azul', 'Marine-Caban-Mantel', 'Cappotto Caban Blu', 'manteau-caban-marine',
'Caban maritime en drap de laine épais. Double boutonnage et coupe ajustée pour une allure maritime chic.',
'Maritime pea coat in thick wool cloth. Double-breasted and fitted cut for chic maritime look.',
'Chaquetón marítimo en paño de lana grueso. Doble botonadura y corte ajustado para look marítimo elegante.',
'Maritimer Caban aus dickem Wollstoff. Zweireihig und taillierter Schnitt für schicken maritimen Look.',
'Caban marittimo in panno di lana spesso. Doppio petto e taglio aderente per look marittimo chic.',
980.00, 'homme', 'manteaux',
'80% Laine, 20% Polyamide', '80% Wool, 20% Polyamide', '80% Lana, 20% Poliamida', '80% Wolle, 20% Polyamid', '80% Lana, 20% Poliammide',
ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Marine'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Polo en Coton Piqué', 'Cotton Piqué Polo', 'Polo de Algodón Piqué', 'Baumwoll-Piqué-Polo', 'Polo in Cotone Piqué', 'polo-coton-pique',
'Polo classique en coton piqué premium. Coupe slim et détails raffinés pour un style décontracté élégant.',
'Classic polo in premium cotton piqué. Slim fit and refined details for elegant casual style.',
'Polo clásico en algodón piqué premium. Corte slim y detalles refinados para estilo casual elegante.',
'Klassisches Polo aus Premium-Baumwoll-Piqué. Schmale Passform und raffinierte Details für eleganten Casual-Stil.',
'Polo classico in cotone piqué premium. Taglio slim e dettagli raffinati per stile casual elegante.',
180.00, 'homme', 'polos',
'100% Coton Piqué', '100% Cotton Piqué', '100% Algodón Piqué', '100% Baumwoll-Piqué', '100% Cotone Piqué',
ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Blanc', 'Marine', 'Gris Chiné', 'Noir'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Derbies en Cuir', 'Leather Derby Shoes', 'Zapatos Derby de Cuero', 'Leder-Derby-Schuhe', 'Scarpe Derby in Pelle', 'derbies-cuir',
'Derbies élégantes en cuir box calf. Cousu Goodyear et finitions artisanales pour une qualité exceptionnelle.',
'Elegant derby shoes in box calf leather. Goodyear welted and artisanal finishes for exceptional quality.',
'Zapatos Derby elegantes en cuero box calf. Cosido Goodyear y acabados artesanales para calidad excepcional.',
'Elegante Derby-Schuhe aus Box-Calf-Leder. Goodyear-rahmengenäht und handwerkliche Verarbeitung für außergewöhnliche Qualität.',
'Scarpe Derby eleganti in pelle box calf. Cuciture Goodyear e finiture artigianali per qualità eccezionale.',
580.00, 'homme', 'chaussures',
'Tige: Cuir Box Calf, Doublure: Cuir, Semelle: Cuir', 'Upper: Box Calf Leather, Lining: Leather, Sole: Leather', 'Parte superior: Cuero Box Calf, Forro: Cuero, Suela: Cuero', 'Obermaterial: Box-Calf-Leder, Futter: Leder, Sohle: Leder', 'Tomaia: Pelle Box Calf, Fodera: Pelle, Suola: Pelle',
ARRAY['40', '41', '42', '43', '44', '45'], ARRAY['Noir', 'Marron', 'Cognac'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Sneakers en Cuir Blanc', 'White Leather Sneakers', 'Zapatillas de Cuero Blanco', 'Weiße Leder-Sneakers', 'Sneaker in Pelle Bianca', 'sneakers-cuir-blanc',
'Sneakers minimalistes en cuir blanc premium. Design épuré et confort optimal pour un style urbain raffiné.',
'Minimalist sneakers in premium white leather. Clean design and optimal comfort for refined urban style.',
'Zapatillas minimalistas en cuero blanco premium. Diseño limpio y comodidad óptima para estilo urbano refinado.',
'Minimalistische Sneakers aus Premium-Leder in Weiß. Klares Design und optimaler Komfort für raffinierten urbanen Stil.',
'Sneaker minimaliste in pelle bianca premium. Design pulito e comfort ottimale per stile urbano raffinato.',
380.00, 'homme', 'chaussures',
'Tige: Cuir Pleine Fleur, Doublure: Textile, Semelle: Caoutchouc', 'Upper: Full-Grain Leather, Lining: Textile, Sole: Rubber', 'Parte superior: Cuero Grano Completo, Forro: Textil, Suela: Caucho', 'Obermaterial: Vollleder, Futter: Textil, Sohle: Gummi', 'Tomaia: Pelle Pieno Fiore, Fodera: Tessuto, Suola: Gomma',
ARRAY['40', '41', '42', '43', '44', '45'], ARRAY['Blanc'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, true),

-- More Accessories
('Portefeuille en Cuir', 'Leather Wallet', 'Cartera de Cuero', 'Leder-Geldbörse', 'Portafoglio in Pelle', 'portefeuille-cuir',
'Portefeuille compact en cuir saffiano. Multiples compartiments et protection RFID intégrée.',
'Compact wallet in saffiano leather. Multiple compartments and integrated RFID protection.',
'Cartera compacta en cuero saffiano. Múltiples compartimentos y protección RFID integrada.',
'Kompakte Geldbörse aus Saffianoleder. Mehrere Fächer und integrierter RFID-Schutz.',
'Portafoglio compatto in pelle saffiano. Multipli scomparti e protezione RFID integrata.',
220.00, 'accessoires', 'petite-maroquinerie',
'100% Cuir Saffiano', '100% Saffiano Leather', '100% Cuero Saffiano', '100% Saffianoleder', '100% Pelle Saffiano',
ARRAY['Unique'], ARRAY['Noir', 'Marine', 'Cognac'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Montre Automatique', 'Automatic Watch', 'Reloj Automático', 'Automatikuhr', 'Orologio Automatico', 'montre-automatique',
'Montre automatique au design minimaliste. Boîtier en acier inoxydable et bracelet en cuir italien.',
'Automatic watch with minimalist design. Stainless steel case and Italian leather strap.',
'Reloj automático con diseño minimalista. Caja de acero inoxidable y correa de cuero italiano.',
'Automatikuhr mit minimalistischem Design. Edelstahlgehäuse und italienisches Lederarmband.',
'Orologio automatico dal design minimalista. Cassa in acciaio inossidabile e cinturino in pelle italiana.',
1850.00, 'accessoires', 'montres',
'Boîtier: Acier Inox, Bracelet: Cuir Italien', 'Case: Stainless Steel, Strap: Italian Leather', 'Caja: Acero Inoxidable, Correa: Cuero Italiano', 'Gehäuse: Edelstahl, Armband: Italienisches Leder', 'Cassa: Acciaio Inox, Cinturino: Pelle Italiana',
ARRAY['Unique'], ARRAY['Argenté', 'Or Rose', 'Noir'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
true, false),

('Chapeau Fedora', 'Fedora Hat', 'Sombrero Fedora', 'Fedora-Hut', 'Cappello Fedora', 'chapeau-fedora',
'Chapeau fedora en feutre de laine. Élégance intemporelle et finitions raffinées pour parfaire votre style.',
'Fedora hat in wool felt. Timeless elegance and refined finishes to perfect your style.',
'Sombrero fedora en fieltro de lana. Elegancia atemporal y acabados refinados para perfeccionar tu estilo.',
'Fedora-Hut aus Wollfilz. Zeitlose Eleganz und raffinierte Verarbeitung zur Perfektionierung Ihres Stils.',
'Cappello fedora in feltro di lana. Eleganza senza tempo e finiture raffinate per perfezionare il tuo stile.',
280.00, 'accessoires', 'chapeaux',
'100% Laine Feutrée', '100% Wool Felt', '100% Fieltro de Lana', '100% Wollfilz', '100% Feltro di Lana',
ARRAY['S', 'M', 'L'], ARRAY['Gris', 'Noir', 'Camel'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Gants en Cuir Doublés', 'Lined Leather Gloves', 'Guantes de Cuero Forrados', 'Gefütterte Lederhandschuhe', 'Guanti in Pelle Foderati', 'gants-cuir-doubles',
'Gants en cuir d''agneau souple doublés cachemire. Élégance et chaleur pour affronter l''hiver.',
'Soft lambskin leather gloves lined with cashmere. Elegance and warmth to face winter.',
'Guantes de cuero de cordero suave forrados con cachemira. Elegancia y calidez para enfrentar el invierno.',
'Weiche Lammlederhandschuhe mit Kaschmirfutter. Eleganz und Wärme für den Winter.',
'Guanti in morbida pelle d''agnello foderati in cashmere. Eleganza e calore per affrontare l''inverno.',
180.00, 'accessoires', 'gants',
'Cuir: Agneau, Doublure: Cachemire', 'Leather: Lambskin, Lining: Cashmere', 'Cuero: Cordero, Forro: Cachemira', 'Leder: Lammleder, Futter: Kaschmir', 'Pelle: Agnello, Fodera: Cashmere',
ARRAY['S', 'M', 'L', 'XL'], ARRAY['Noir', 'Marron', 'Gris'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

-- Women's Jewelry-inspired accessories
('Collier Minimaliste', 'Minimalist Necklace', 'Collar Minimalista', 'Minimalistische Halskette', 'Collana Minimalista', 'collier-minimaliste',
'Collier délicat en or vermeil. Design minimaliste et élégant pour sublimer votre décolleté.',
'Delicate vermeil gold necklace. Minimalist and elegant design to enhance your neckline.',
'Collar delicado en oro vermeil. Diseño minimalista y elegante para realzar tu escote.',
'Zarte Halskette aus vergoldetem Silber. Minimalistisches und elegantes Design für Ihren Ausschnitt.',
'Collana delicata in oro vermeil. Design minimalista ed elegante per valorizzare la scollatura.',
320.00, 'accessoires', 'bijoux',
'Or Vermeil 18K sur Argent 925', '18K Vermeil Gold on 925 Silver', 'Oro Vermeil 18K sobre Plata 925', '18K Vermeil-Gold auf 925er Silber', 'Oro Vermeil 18K su Argento 925',
ARRAY['Unique'], ARRAY['Or', 'Argent', 'Or Rose'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

('Boucles d''Oreilles Créoles', 'Hoop Earrings', 'Pendientes Aro', 'Creolen-Ohrringe', 'Orecchini a Cerchio', 'boucles-oreilles-creoles',
'Boucles d''oreilles créoles en or 14 carats. Finition polie et fermoir sécurisé pour un port confortable.',
'Hoop earrings in 14-karat gold. Polished finish and secure clasp for comfortable wear.',
'Pendientes de aro en oro de 14 quilates. Acabado pulido y cierre seguro para uso cómodo.',
'Creolen-Ohrringe aus 14-karätigem Gold. Polierte Oberfläche und sicherer Verschluss für bequemes Tragen.',
'Orecchini a cerchio in oro 14 carati. Finitura lucida e chiusura sicura per un uso confortevole.',
480.00, 'accessoires', 'bijoux',
'Or 14 Carats', '14-Karat Gold', 'Oro 14 Quilates', '14-karätiges Gold', 'Oro 14 Carati',
ARRAY['Unique'], ARRAY['Or Jaune', 'Or Blanc', 'Or Rose'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

-- Final items to reach 30 products
('Pantalon Large Fluide', 'Wide-Leg Fluid Trousers', 'Pantalón Ancho Fluido', 'Weite fließende Hose', 'Pantalone Ampio Fluido', 'pantalon-large-fluide',
'Pantalon large à la coupe fluide. Taille haute et tombé élégant pour une silhouette allongée.',
'Wide-leg trousers with fluid cut. High waist and elegant drape for elongated silhouette.',
'Pantalón ancho con corte fluido. Cintura alta y caída elegante para silueta alargada.',
'Weite Hose mit fließendem Schnitt. Hohe Taille und eleganter Fall für gestreckte Silhouette.',
'Pantalone ampio dal taglio fluido. Vita alta e caduta elegante per silhouette allungata.',
450.00, 'femme', 'bas',
'75% Viscose, 25% Lin', '75% Viscose, 25% Linen', '75% Viscosa, 25% Lino', '75% Viskose, 25% Leinen', '75% Viscosa, 25% Lino',
ARRAY['34', '36', '38', '40', '42', '44'], ARRAY['Écru', 'Noir', 'Terracotta'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true),

('Gilet Sans Manches', 'Sleeveless Vest', 'Chaleco Sin Mangas', 'Ärmellose Weste', 'Gilet Senza Maniche', 'gilet-sans-manches',
'Gilet long sans manches en laine fine. Pièce de layering parfaite pour les mi-saisons.',
'Long sleeveless vest in fine wool. Perfect layering piece for mid-seasons.',
'Chaleco largo sin mangas en lana fina. Pieza perfecta para superponer en entretiempo.',
'Lange ärmellose Weste aus feiner Wolle. Perfektes Layering-Stück für Übergangszeiten.',
'Gilet lungo senza maniche in lana fine. Pezzo perfetto per stratificare nelle mezze stagioni.',
380.00, 'femme', 'hauts',
'90% Laine, 10% Cachemire', '90% Wool, 10% Cashmere', '90% Lana, 10% Cachemira', '90% Wolle, 10% Kaschmir', '90% Lana, 10% Cashmere',
ARRAY['XS', 'S', 'M', 'L', 'XL'], ARRAY['Beige', 'Gris', 'Camel'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Veste en Jean Premium', 'Premium Denim Jacket', 'Chaqueta Vaquera Premium', 'Premium-Jeansjacke', 'Giacca in Denim Premium', 'veste-jean-premium',
'Veste en denim japonais premium. Coupe moderne et détails raffinés pour réinventer un classique.',
'Premium Japanese denim jacket. Modern cut and refined details to reinvent a classic.',
'Chaqueta de denim japonés premium. Corte moderno y detalles refinados para reinventar un clásico.',
'Premium-Jeansjacke aus japanischem Denim. Moderner Schnitt und raffinierte Details zur Neuerfindung eines Klassikers.',
'Giacca in denim giapponese premium. Taglio moderno e dettagli raffinati per reinventare un classico.',
420.00, 'homme', 'vestes',
'100% Coton Denim Japonais', '100% Japanese Denim Cotton', '100% Algodón Denim Japonés', '100% Japanische Denim-Baumwolle', '100% Cotone Denim Giapponese',
ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['Brut', 'Délavé', 'Noir'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, false),

('Sac Bandoulière Cuir', 'Leather Crossbody Bag', 'Bolso Bandolera de Cuero', 'Leder-Umhängetasche', 'Borsa a Tracolla in Pelle', 'sac-bandouliere-cuir',
'Sac bandoulière compact en cuir lisse. Design épuré et bandoulière ajustable pour un port confortable.',
'Compact crossbody bag in smooth leather. Clean design and adjustable strap for comfortable wear.',
'Bolso bandolera compacto en cuero liso. Diseño limpio y correa ajustable para uso cómodo.',
'Kompakte Umhängetasche aus glattem Leder. Klares Design und verstellbarer Riemen für bequemes Tragen.',
'Borsa a tracolla compatta in pelle liscia. Design pulito e tracolla regolabile per un uso confortevole.',
520.00, 'accessoires', 'sacs',
'100% Cuir de Veau Lisse', '100% Smooth Calfskin Leather', '100% Cuero de Ternera Liso', '100% Glattes Kalbsleder', '100% Pelle di Vitello Liscia',
ARRAY['Unique'], ARRAY['Noir', 'Camel', 'Bordeaux'],
ARRAY['/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600', '/placeholder.svg?height=800&width=600'],
false, true);
